var list = [
	{
		name: "KIOKU",
		artist: "日廻り(向日葵)",
		url: "https://kusarinoshojo.space/file/日廻り.ogg",
		cover: "https://files.catbox.moe/4e16pp.jfif",
	},
	{
		name: "KIOKU",
		artist: "snowic",
		url: "https://kusarinoshojo.space/file/snowic.ogg",
		cover: "https://files.catbox.moe/4e16pp.jfif",
	},
	{
		name: "KIOKU",
		artist: "evergreen",
		url: "https://kusarinoshojo.space/file/evergreen.ogg",
		cover: "https://files.catbox.moe/4e16pp.jfif",
	},
	{
		name: "KIOKU",
		artist: "tuyu",
		url: "https://kusarinoshojo.space/file/tuyu.ogg",
		cover: "https://files.catbox.moe/4e16pp.jfif",
	},
	{
		name: "Seren",
		artist: "fill up",
		url: "https://kusarinoshojo.space/file/fillup.ogg",
		cover: "https://i.ytimg.com/vi/BgNVwiX7K8E/hq720.jpg",
	},
	{
		name: "Seren",
		artist: "曖愛傘",
		url: "https://kusarinoshojo.space/file/曖愛傘.ogg",
		cover: "https://files.catbox.moe/g774in.jfif",
	},
	{
		name: "Seren",
		artist: "Just Love (feat. PSYQUI)",
		url: "https://kusarinoshojo.space/file/Just Love (feat. PSYQUI).ogg",
		cover: "https://files.catbox.moe/g774in.jfif",
	},
	{
		name: "Love-in-a-Mist",
		artist: "prologue.01",
		url: "https://kusarinoshojo.space/file/prologue.01 - 東 雪蓮.ogg",
		cover: "https://i.ytimg.com/vi/eLfhJmhYOcA/hqdefault.jpg",
	},
	{
		name: "Seren",
		artist: "life hacks",
		url: "https://kusarinoshojo.space/file/life hacks.ogg",
		cover: "https://files.catbox.moe/g774in.jfif",
	},
	{
		name: "Seren",
		artist: "intarnet",
		url: "https://kusarinoshojo.space/file/intarnet (feat. Yaca).ogg",
		cover: "https://files.catbox.moe/g774in.jfif",
	},
	{
		name: "Seren",
		artist: "hesitation(犹豫不决)",
		url: "https://kusarinoshojo.space/file/hesitation (feat. TEMPLIME).ogg",
		cover: "https://files.catbox.moe/g774in.jfif",
	},
	{
		name: "Seren",
		artist: "ひめさま(公主)",
		url: "https://kusarinoshojo.space/file/ひめさま (feat. nyankobrq).ogg",
		cover: "https://files.catbox.moe/g774in.jfif",
	},
	{
		name: "Seren",
		artist: "アイシテル(我爱你)",
		url: "https://kusarinoshojo.space/file/アイシテル.ogg",
		cover: "https://files.catbox.moe/g774in.jfif",
	},
	{
		name: "Seren",
		artist: "りそうのせかい(理想世界)",
		url: "https://kusarinoshojo.space/file/りそうのせかい (feat. higma).ogg",
		cover: "https://files.catbox.moe/g774in.jfif",
	},
	{
		name: "Cover",
		artist: "ド屑(人渣)",
		url: "https://kusarinoshojo.space/file/ド屑  東 雪蓮(cover).ogg",
		cover: "https://i.ytimg.com/vi/rXUqg9DSpa0/hqdefault.jpg",
	},
	{
		name: "Cover",
		artist: "NIGHTWALK(夜行)",
		url: "https://kusarinoshojo.space/file/NIGHTWALK feat.23.exe - 東 雪蓮.ogg",
		cover: "https://kusarinoshojo.space/file/nightwalk.jpg",
	},
	{
		name: "Cover",
		artist: "エイリアンズ(外星人)",
		url: "https://kusarinoshojo.space/file/エイリアンズ - キリンジ  東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/エイリアンズ.jpg",
	},
	{
		name: "Cover",
		artist: "Babyblue Lip",
		url: "https://kusarinoshojo.space/file/Babyblue Lip  東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/BabyblueLip.jpg",
	},
	{
		name: "Cover",
		artist: "CHO-DARI",
		url: "https://kusarinoshojo.space/file/CHO-DARI-  東 雪蓮 (cover).ogg",
		cover: "https://kusarinoshojo.space/file/CHO-DARI-.jpg",
	},
	{
		name: "Cover",
		artist: "Gimme×Gimme",
		url: "https://kusarinoshojo.space/file/Gimme×Gimme  東 雪蓮×小柔 (cover).ogg",
		cover: "https://kusarinoshojo.space/file/Gimme×Gimme.jpg",
	},
	{
		name: "Cover",
		artist: "Heal Me",
		url: "https://kusarinoshojo.space/file/Heal Me  東 雪蓮 (cover).ogg",
		cover: "https://kusarinoshojo.space/file/HealMe.jpg",
	},
	{
		name: "Cover",
		artist: "Peaches",
		url: "https://kusarinoshojo.space/file/Justin Bieber - Peaches ft. Daniel Caesar, Giveon 東 雪蓮 (cover).ogg",
		cover: "https://kusarinoshojo.space/file/Peaches.jpg",
	},
	{
		name: "Cover",
		artist: "kiki vivi lily",
		url: "https://kusarinoshojo.space/file/kiki vivi lily - 80denier 東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/kikivivilily.jpg",
	},
	{
		name: "Cover",
		artist: "Overthinking",
		url: "https://kusarinoshojo.space/file/Overthinking - 東 雪蓮.ogg",
		cover: "https://kusarinoshojo.space/file/Overthinking.jpg",
	},
	{
		name: "Cover",
		artist: "Plastic Love",
		url: "https://kusarinoshojo.space/file/Plastic Love - Mariya Takeuchi  東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/PlasticLove.jpg",
	},
	{
		name: "Cover",
		artist: "SAY SO",
		url: "https://kusarinoshojo.space/file/SAY SO - Doja Cat [Japanese Version]   東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/sayso.jpg",
	},
	{
		name: "Cover",
		artist: "No.1",
		url: "https://kusarinoshojo.space/file/tofubeats - No.1  東 雪蓮 (cover).ogg",
		cover: "https://kusarinoshojo.space/file/No.1.jpg",
	},
	{
		name: "Cover",
		artist: "melt bitter",
		url: "https://kusarinoshojo.space/file/さとうもか - melt bitter  東 雪蓮 (cover).ogg",
		cover: "https://kusarinoshojo.space/file/meltbitter.jpg",
	},
	{
		name: "Cover",
		artist: "さようなら、花泥棒さん(再见，偷花人)",
		url: "https://kusarinoshojo.space/file/さようなら、花泥棒さん  東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/さようなら、花泥棒さん.jpg",
	},
	{
		name: "Cover",
		artist: "じゅくじゅく",
		url: "https://kusarinoshojo.space/file/じゅくじゅく 東 雪蓮 (cover).ogg",
		cover: "https://kusarinoshojo.space/file/じゅくじゅく.jpg",
	},
	{
		name: "Cover",
		artist: "ルーマー",
		url: "https://kusarinoshojo.space/file/ルーマー  東雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/rumu.jpg",
	},
	{
		name: "Cover",
		artist: "ヴァンパイア(吸血鬼)",
		url: "https://kusarinoshojo.space/file/ヴァンパイア 東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/ヴァンパイア.jpg",
	},
	{
		name: "Cover",
		artist: "シル・ヴ・プレジデント(如果我成为大总统)",
		url: "https://kusarinoshojo.space/file/三ヶ国語で「シル・ヴ・プレジデント」を歌ってみた。.ogg",
		cover: "https://kusarinoshojo.space/file/三ヶ国語で「シル・ヴ・プレジデント」を歌ってみた。.jpg",
	},
	{
		name: "Cover",
		artist: "同担☆拒否",
		url: "https://kusarinoshojo.space/file/同担☆拒否   東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/同担☆拒否.jpg",
	},
	{
		name: "Cover",
		artist: "寄り酔い(倚醉)",
		url: "https://kusarinoshojo.space/file/寄り酔い  東 雪蓮 (cover).ogg",
		cover: "https://kusarinoshojo.space/file/寄り酔い.jpg",
	},
	{
		name: "Cover",
		artist: "食虫植物",
		url: "https://kusarinoshojo.space/file/食虫植物 東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/食虫植物.jpg",
	},
	{
		name: "Cover",
		artist: "Angels",
		url: "https://kusarinoshojo.space/file/Angels   東 雪蓮(cover).ogg",
		cover: "https://kusarinoshojo.space/file/angels.jpg",
	},
];
